import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import createCalendar from 'ical-generator';
import QRCode from 'qrcode';

export interface ProfileData {
  fullName: string;
  bio: string;
  email?: string;
  phone?: string;
  location?: string;
  website?: string;
  profession?: string;
  experience?: string;
  repositories?: Array<{
    name: string;
    url: string;
    description?: string;
  }>;
}

/**
 * Export profile as PDF
 */
export async function exportToPDF(profileData: ProfileData, filename: string = 'profile.pdf') {
  try {
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    let yPosition = 20;

    // Title
    pdf.setFontSize(24);
    pdf.setTextColor(88, 0, 212); // primary color
    pdf.text(profileData.fullName, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 12;

    // Bio
    pdf.setFontSize(11);
    pdf.setTextColor(100, 100, 100);
    pdf.text(profileData.bio, 20, yPosition, { maxWidth: pageWidth - 40 });
    yPosition += 15;

    // Contact Info
    pdf.setFontSize(10);
    pdf.setTextColor(0, 0, 0);

    const contactInfo = [];
    if (profileData.email) contactInfo.push(`Email: ${profileData.email}`);
    if (profileData.phone) contactInfo.push(`Phone: ${profileData.phone}`);
    if (profileData.location) contactInfo.push(`Location: ${profileData.location}`);
    if (profileData.website) contactInfo.push(`Website: ${profileData.website}`);

    contactInfo.forEach(info => {
      pdf.text(info, 20, yPosition);
      yPosition += 8;
    });

    yPosition += 5;

    // Professional Info
    if (profileData.profession) {
      pdf.setFontSize(12);
      pdf.setTextColor(88, 0, 212);
      pdf.text('Professional Profile', 20, yPosition);
      yPosition += 8;

      pdf.setFontSize(10);
      pdf.setTextColor(0, 0, 0);
      pdf.text(`Profession: ${profileData.profession}`, 25, yPosition);
      yPosition += 6;
      if (profileData.experience) {
        pdf.text(`Experience: ${profileData.experience}`, 25, yPosition);
        yPosition += 6;
      }
    }

    yPosition += 5;

    // Repositories
    if (profileData.repositories && profileData.repositories.length > 0) {
      pdf.setFontSize(12);
      pdf.setTextColor(88, 0, 212);
      pdf.text('Featured Projects', 20, yPosition);
      yPosition += 8;

      profileData.repositories.forEach((repo, index) => {
        if (yPosition > pageHeight - 20) {
          pdf.addPage();
          yPosition = 20;
        }

        pdf.setFontSize(10);
        pdf.setTextColor(0, 0, 0);
        pdf.text(`${index + 1}. ${repo.name}`, 25, yPosition);
        yPosition += 6;

        if (repo.description) {
          pdf.setFontSize(9);
          pdf.setTextColor(100, 100, 100);
          pdf.text(repo.description, 30, yPosition, { maxWidth: pageWidth - 50 });
          yPosition += 6;
        }

        pdf.setFontSize(9);
        pdf.setTextColor(88, 0, 212);
        pdf.textWithLink(repo.url, 30, yPosition, { pageNumber: 1 });
        yPosition += 8;
      });
    }

    // Footer
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text('Generated by BioPath Pro', pageWidth / 2, pageHeight - 10, { align: 'center' });

    pdf.save(filename);
    return true;
  } catch (error) {
    console.error('PDF export error:', error);
    throw new Error('Failed to export PDF');
  }
}

/**
 * Export profile as VCF (vCard format)
 */
export function exportToVCF(profileData: ProfileData, filename: string = 'contact.vcf') {
  try {
    const vcf = generateVCF(profileData);
    const element = document.createElement('a');
    element.setAttribute('href', `data:text/vcard;charset=utf-8,${encodeURIComponent(vcf)}`);
    element.setAttribute('download', filename);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    return true;
  } catch (error) {
    console.error('VCF export error:', error);
    throw new Error('Failed to export VCF');
  }
}

/**
 * Generate VCF content
 */
function generateVCF(profileData: ProfileData): string {
  let vcf = 'BEGIN:VCARD\n';
  vcf += 'VERSION:3.0\n';
  vcf += `FN:${profileData.fullName}\n`;
  vcf += `N:${profileData.fullName.split(' ').reverse().join(';')}\n`;

  if (profileData.email) {
    vcf += `EMAIL;TYPE=INTERNET:${profileData.email}\n`;
  }
  if (profileData.phone) {
    vcf += `TEL:${profileData.phone}\n`;
  }
  if (profileData.location) {
    vcf += `ADR:;;${profileData.location}\n`;
  }
  if (profileData.website) {
    vcf += `URL:${profileData.website}\n`;
  }
  if (profileData.bio) {
    vcf += `NOTE:${profileData.bio}\n`;
  }

  vcf += 'END:VCARD\n';
  return vcf;
}

/**
 * Export profile as iCal
 */
export function exportToICal(profileData: ProfileData, filename: string = 'profile.ics') {
  try {
    const calendar = createCalendar({
      name: `${profileData.fullName}'s Profile`,
      description: profileData.bio,
    });

    // Add event for profile creation
    calendar.createEvent({
      summary: `${profileData.fullName}'s Professional Profile`,
      description: profileData.bio,
      start: new Date(),
      duration: { hours: 1 },
      url: profileData.website || '',
    } as any);

    const icsContent = calendar.toString();
    const element = document.createElement('a');
    element.setAttribute('href', `data:text/calendar;charset=utf-8,${encodeURIComponent(icsContent)}`);
    element.setAttribute('download', filename);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    return true;
  } catch (error) {
    console.error('iCal export error:', error);
    throw new Error('Failed to export iCal');
  }
}

/**
 * Generate QR code
 */
export async function generateQRCode(text: string, size: number = 300): Promise<string> {
  try {
    const qrCode = await QRCode.toDataURL(text, {
      errorCorrectionLevel: 'H',
      type: 'image/png',
      quality: 0.95,
      margin: 1,
      width: size,
    });
    return qrCode;
  } catch (error) {
    console.error('QR code generation error:', error);
    throw new Error('Failed to generate QR code');
  }
}

/**
 * Export profile as HTML (shareable)
 */
export function exportToHTML(profileData: ProfileData): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${profileData.fullName}'s Profile</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 20px; background: #f9f9f9; }
    .container { max-width: 600px; margin: 0 auto; background: white; padding: 40px; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
    h1 { margin: 0; color: #5800d4; }
    .bio { color: #666; margin: 10px 0 20px; }
    .contact { margin: 20px 0; }
    .contact p { margin: 5px 0; }
    .projects { margin-top: 30px; }
    .project { margin: 15px 0; padding: 15px; background: #f5f5f5; border-radius: 8px; }
    .project h3 { margin: 0 0 5px; }
  </style>
</head>
<body>
  <div class="container">
    <h1>${profileData.fullName}</h1>
    <p class="bio">${profileData.bio}</p>
    
    <div class="contact">
      ${profileData.email ? `<p>📧 <a href="mailto:${profileData.email}">${profileData.email}</a></p>` : ''}
      ${profileData.location ? `<p>📍 ${profileData.location}</p>` : ''}
      ${profileData.website ? `<p>🌐 <a href="${profileData.website}">${profileData.website}</a></p>` : ''}
    </div>

    ${profileData.repositories && profileData.repositories.length > 0 ? `
    <div class="projects">
      <h2>Featured Projects</h2>
      ${profileData.repositories.map(repo => `
        <div class="project">
          <h3>${repo.name}</h3>
          ${repo.description ? `<p>${repo.description}</p>` : ''}
          <a href="${repo.url}">View on GitHub →</a>
        </div>
      `).join('')}
    </div>
    ` : ''}
  </div>
</body>
</html>
  `.trim();
}
